# Example for using the keymap-drawer ZMK user config workflow
name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:               # automatically run on changes to following paths
    paths:
      - "config/*.keymap"
      - "keymap_drawer_config.yaml"

jobs:
  draw:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write  # allow workflow to commit to the repo
    with:
      keymap_patterns: "config/*.keymap"        # path to the keymaps to parse
      config_path: "keymap-drawer/keymap_drawer_conf.yaml"  # config file, ignored if not exists
      output_folder: "keymap-drawer"            # path to save produced SVG and keymap YAML files
      commit_message: "[Draw] ${{ github.event.head_commit.message }} [skip ci]"            # commit message

